// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:132ceba5-cb82-4a7b-8540-64cd95fcaa14",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gRf0WTrFs",
    "aws_user_pools_web_client_id": "mnc9p2jim5l95k83ceq88tbd2",
    "aws_appsync_graphqlEndpoint": "https://7fcem2eeavaotbehhkgdw5des4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xcexwh6ssjdz7jye7o3y6qoshq"
};


export default awsmobile;
